import './brand-logo.js';
import './hero-section.js';
import './loader-section.js';
import './message-section.js';
import './navigation-menu.js';
import './restaurant-item.js';
import './restaurant-list-section.js';
import './testimonials-section.js';
import './features-section.js';
